### ISSUE TITLE
[CodeGen] Unknown scalar kind decimal

### ISSUE THREAD

**Issue by asaflevi-ms** [Azure/autorest.typescript#2187]
Hi 
Radiology Insights is a new model in health insights service new API Version.
The new version is a bit complex and we had some issues with other languages.

Please check this tsp-location:
https://github.com/asaflevi-ms/azure-sdk-for-js/blob/asaflevi/healthinsights-radiologyinsights-js-sdk/sdk/healthinsights/health-insights-radiologyinsights-rest/tsp-location.yaml 

I tried to generate JS SDK and got the below error:

ExternalError: Emitter "@azure-tools/typespec-ts" crashed! This is a bug.
Error: Unknown scalar kind decimal

Once you resolve this, please try to generate the SDK and make sure it is generated as there are more issues down the road.

**Comment by MaryGao** [comment]
@kazrael2119 Could you try to update the tsp to the latest in our smoke test?

**Comment by qiaozha** [comment]
This should have been resolved in https://www.npmjs.com/package/@azure-tools/typespec-ts/v/0.20.0

**Comment by asaflevi-ms** [comment]
@qiaozha 
Still fail.
I think that emmiter-package.json is not updated in azure-sdk-for-js.

**Comment by qiaozha** [comment]
I have this pr to update it. https://github.com/Azure/azure-sdk-for-js/pull/28249

**Comment by lirenhe** [comment]
PR https://github.com/Azure/azure-sdk-for-js/pull/28249 merged.
