### ISSUE TITLE
TS2339 - Property 'parsedbody'  does not exist on HttpOperationResponse

### ISSUE THREAD

**Issue by chieftn** [Azure/autorest.typescript#76]
autorest output of  file [https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/iothub/resource-manager/Microsoft.Devices/stable/2018-04-01/iothub.json](url) with following specifications:

typescript.azure-arm: true
typescript:
    output-folder: ./lib/
license-header: MICROSOFT_MIT_NO_VERSION
add-credentials: true
package-name: microsoft-azure-devices-iothub-controlplane
input-file: ./src/2018-04-01/iothub.json
package-version: 2018.04.01.01
generate-metadata: true

fails on tsc.  Receiving large number of TS2339.  Noticed the issue is resolved when moving the dependency from ms-rest-js 0.2.1 to 0.3.0.  Trying to understand if this is user error or if an issue is present.  

Loading AutoRest core      'C:\Users\rkessler\.autorest\@microsoft.azure_autorest-core@2.0.4277\node_modules\@microsoft.azure\autorest-core\dist' (2.0.4277)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.176)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.1.23->2.1.23)

New to tech -- so guidance appreciated.

**Comment by RikkiGibson** [comment]
`bodyAsJson` was renamed to `parsedBody` in ms-rest-js and we recently updated the AutoRest generator to use this new name. The best solution is to use the latest ms-rest-js. Sorry for the inconvenience.

**Comment by daschult** [comment]
This has been fixed in the most recent preview versions of `ms-rest-js` and `autorest.typescript`.

**Comment by clouddra** [comment]
@daschult I am still encountering this issue. Can you provide an example of the working cli command to run?

**Comment by daschult** [comment]
@clouddra If you use the following line on the command line:
`autorest --typescript --use=@microsoft.azure/autorest.typescript@preview <the rest of your command>`
then it will use the latest preview version of the AutoRest TypeScript generator. If you're not using the `--generate-metadata` command line argument, then you'll also need to go into your package.json file and update your `ms-rest-js` dependency to use the latest preview version as well ([0.7.206](https://www.npmjs.com/package/ms-rest-js/v/0.7.206) as of this comment).

**Comment by RikkiGibson** [comment]
If you look in the generated operation, e.g. getWithHttpOperationResponse(), do you see parsedBody being set in the code?

**Comment by clouddra** [comment]
`parsedBody` is not set. `bodyAsText` is set though.

**Comment by RikkiGibson** [comment]
I would try forcing using the latest generator and runtime with `--use=@microsoft.azure/autorest.typescript@preview` in autorest and `npm i ms-rest-js@preview` in your package.

**Comment by tomlm** [comment]
I see this if the REST API doesn't set the content-type to "application/json".  In my case it was “application/octet-stream”, which causes the AutoRest generated code to not parse the content as json into the parsedBody property.

**Comment by RikkiGibson** [comment]
We might be able to do something like prefer the Content-Type given in `"produces"` in Swagger to the Content-Type we see at runtime. Do you mind opening an issue for this?
